version: "3"

# noinspection YAMLSchemaValidation
.kotlinSources: &kotlinSources
  - '**/*.kt'

includes:
  github:config:
    taskfile: .github/config/Taskfile.yml
    dir: .github/config

tasks:
  checkFormatting:
    desc: Check formatting for the entire codebase
    deps:
      - github:config:checkFormatting
      - gradleRoot:checkFormatting

  fixFormatting:
    desc: Fix formatting for the entire codebase
    deps:
      - github:config:fixFormatting
      - gradleRoot:fixFormatting

  analyzeStatically:
    desc: Statically analyze the entire codebase
    deps:
      - github:config:lint
      - gradleRoot:analyzeStatically

  gradleRoot:checkFormatting:
    desc: Check formatting for the root Gradle project
    sources: *kotlinSources
    cmds:
      - ./gradlew ktfmtCheck
    interactive: true

  gradleRoot:fixFormatting:
    desc: Fix formatting for the root Gradle project
    sources: *kotlinSources
    cmds:
      - ./gradlew ktfmtFormat
    interactive: true

  gradleRoot:analyzeStatically:
    desc: Statically analyze the root Gradle project
    sources: *kotlinSources
    cmds:
      - ./gradlew assemble
      - ./gradlew detekt
    interactive: true
